# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: Backlog.app
  password:
  host: localhost

development:
  <<: *default
  database: Backlog.app_development

test:
  <<: *default
  database: Backlog.app_test

# Herokuデプロイ時に再度見直す
production:
  <<: *default
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %> 